import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import { VitePWA } from "vite-plugin-pwa";

// The vault must work with the phone in airplane mode, forever. Everything is
// precached; nothing is fetched at runtime. `connect-src 'none'` is set in the
// deployment headers so the air-gap is visible in devtools — see
// docs/SECURITY.md.
export default defineConfig({
  plugins: [
    react(),
    VitePWA({
      registerType: "autoUpdate",
      workbox: { globPatterns: ["**/*"] },
      // The manifest is served in development too, so the installability test
      // checks the real thing rather than a build artefact nobody looks at.
      devOptions: { enabled: true, type: "module" },
      // Icons are not decoration here: without them Chrome on Android does
      // not offer "add to home screen", and the premise — a spare phone that
      // becomes a signer — stops at a browser tab. Generated by
      // scripts/make-vault-icons.mjs from the same mark the web app draws.
      includeAssets: ["favicon.png", "apple-touch-icon.png"],
      manifest: {
        name: "PixStock Vault",
        short_name: "Vault",
        description: "Offline signer for tokenized stocks. Never connects.",
        display: "standalone",
        orientation: "portrait",
        start_url: "/",
        scope: "/",
        background_color: "#1c1a17",
        theme_color: "#1c1a17",
        icons: [
          { src: "icon-192.png", sizes: "192x192", type: "image/png" },
          { src: "icon-512.png", sizes: "512x512", type: "image/png" },
          {
            src: "icon-maskable-512.png",
            sizes: "512x512",
            type: "image/png",
            purpose: "maskable",
          },
        ],
      },
    }),
  ],
  // Not Vite's default 5173. A service worker is bound to an origin, and
  // every Vite project on this machine shares localhost:5173 — a stale worker
  // from another app will happily serve its own cached page over ours. Seen in
  // practice on 12 Sept; a distinct port removes the whole class of problem.
  server: { port: 5183, strictPort: true },
  preview: { port: 5183, strictPort: true },
});
